services:
  app:
    build: .docker/php
    container_name: php-app
    working_dir: /var/www/html/src
    volumes:
      - ./:/var/www/html:cached
    environment:
      - APP_ENV=local
    depends_on:
      - db
      - redis

  web:
    image: nginx:1.27-alpine
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgis/postgis:16-3.4
    container_name: db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"

volumes:
  db_data:
